[package]
name = "cextauthz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
proxy-wasm = "0.2"
prost = { version = "0.14", default-features = false, features = ["derive", "std"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
