services:
  upstream:
    image: nginx:1.27.5-alpine

  authz-service:
    image: istio/ext-authz:1.30.0-debug

  envoy:
    image: envoyproxy/envoy:v1.30.11
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      # Ensure the WASM module is built first: ./build.sh
      - ../target/wasm32-unknown-unknown/release/cextauthz.wasm:/etc/envoy/cextauthz.wasm
    depends_on:
      - upstream
      - authz-service
